In [76]:
import pandas as pd
import re

df = pd.read_excel("../data/case_02_dataset.xlsx")
df

,date,lang,source,user_id,hashtags,is_quote,mentions,tweet_id,username,verified,...,quoted_tweet_id,quoted_username,user_created_at,user_description,in_reply_to_user_id,user_statuses_count,user_followers_count,user_following_count,in_reply_to_status_id,in_reply_to_screen_name
0,45662.580625,in,dlvr.it,1666303982007111680,[],False,[],1875904106541559808,arinadotid,False,...,NaN,NaN,Wed Jun 07 04:40:18 +0000 2023,Media khas keislaman yang berjejaring dengan m...,NaN,5911.0,110.0,20.0,NaN,NaN
1,45752.567060,in,Twitter Web App,1356909896738820096,"[""PenuhiGiziIndonesia"",""Indonesiaemas"",""AstaCi...",False,[],1908514097764897024,ArifaNidya,False,...,NaN,NaN,Wed Feb 03 10:18:32 +0000 2021,make me special,NaN,5069.0,15.0,25.0,NaN,NaN
2,45671.931933,in,Twitter for Android,553451866,[],False,"[{""name"":""Lambe Waras"",""user_id"":""2905814730"",...",1879292908261794304,ZainAris,False,...,NaN,NaN,Sat Apr 14 11:15:29 +0000 2012,Pemerhati sospol hukum dan ekonomi,2.905815e+09,19762.0,701.0,1103.0,1.879286e+18,abu_waras
3,45715.643438,in,Twitter for Android,1300748401890320384,[],False,"[{""name"":""Tanyarl 💚"",""user_id"":""13316505595189...",1895133428124918272,hereseans,False,...,NaN,NaN,Tue Sep 01 10:52:47 +0000 2020,INTJ,1.750874e+18,20947.0,1977.0,2052.0,1.895126e+18,HukumItb
4,45946.966262,in,Twitter for Android,1910040869513879552,[],False,[],1978962010009223168,revirevii1,False,...,NaN,NaN,Wed Apr 09 18:43:39 +0000 2025,NaN,NaN,1198.0,1002.0,1116.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14995,45744.721424,in,Twitter Web App,1615477539585261568,[],False,"[{""name"":""TahooMan™️"",""user_id"":""1118723550649...",1905670937275687168,N_Vanvan22,False,...,NaN,NaN,Tue Jan 17 22:36:17 +0000 2023,NaN,1.118724e+18,1269.0,8.0,148.0,1.905585e+18,AraituLaki
14996,45929.870012,in,Twitter Web App,53713023,[],False,[],1972766536638312704,BolaNaga,False,...,NaN,NaN,Sat Jul 04 17:10:11 +0000 2009,NaN,NaN,22518.0,806.0,59.0,NaN,NaN
14997,45722.603634,in,Twitter for Android,1080657285842518016,"[""Indonesiadaruratkorupsi"",""IndonesiaGelap""]",False,[],1897655718708433152,wlaha_sarimbit,False,...,NaN,NaN,Thu Jan 03 02:49:09 +0000 2019,suka old school metal...\npernah ngeband gak p...,NaN,24375.0,399.0,391.0,NaN,NaN
14998,45942.862141,in,Twitter Web App,236975456,"[""KluivertOut"",""ErickOut"",""OurMuseJimin"",""afcm...",False,[],1977474727938855168,Ole777Zodiak,False,...,NaN,NaN,Tue Jan 11 20:03:51 +0000 2011,NYAI Weton!,NaN,364.0,19.0,6.0,NaN,NaN
14999,45787.201736,in,Twitter for Android,1849310755797254144,[],False,"[{""name"":""Menuju Indonesia Emas 2045"",""user_id...",1921065287085928704,irfan_zaki13,False,...,NaN,NaN,Thu Oct 24 04:43:57 +0000 2024,Got everything in u,2.377353e+09,621.0,1.0,18.0,1.921042e+18,GenZNusantara

In [77]:
import re
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory
from nltk.tokenize import word_tokenize
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Hp\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\Hp\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [78]:
# cleaning kolom description aja
def clean_descrip(text):
    # lowercase
    text = text.lower()
    # url
    text = re.sub(r'https?://\S+|www\.\S+', '', text)
    # angka dan tanda baca
    text = re.sub(r'[^a-zA-Z0-9\s]', '', text)
    # digit angka
    text = re.sub(r'\d+', '', text)
    # hashtag dan mention
    text = re.sub(r'@\w+|#\w+', '', text)
    # spasi berlebih
    text = re.sub(r'\s+', ' ', text).strip()
    
    return text
    

df['cleaning'] = df['full_text'].astype(str).apply(clean_descrip)

display(df[['full_text', 'cleaning']].head())

,full_text,cleaning
0,Surat Edaran (SE) Ditjen Pendis Kemenag Nomor ...,surat edaran se ditjen pendis kemenag nomor ta...
1,PROGRAM MAKAN BERGIZI GRATIS UNTUK ANEUK ACEH\...,program makan bergizi gratis untuk aneuk aceh ...
2,@abu_waras @prabowo Sdh pertengahan Januari 20...,abuwaras prabowo sdh pertengahan januari sampa...
3,@bahlilngntot @tanyakanrl Agen mbg,bahlilngntot tanyakanrl agen mbg
4,Program MBG = bukan bisnis. Ini gerakan sosial...,program mbg bukan bisnis ini gerakan sosial ya...

In [79]:
def tokenize_text(text):
    if isinstance(text, str):
        return text.split()
    else:
        return []

df['tokens'] = df['cleaning'].apply(tokenize_text)

display(df[['full_text', 'cleaning', 'tokens']].head())

,full_text,cleaning,tokens
0,Surat Edaran (SE) Ditjen Pendis Kemenag Nomor ...,surat edaran se ditjen pendis kemenag nomor ta...,"[surat, edaran, se, ditjen, pendis, kemenag, n..."
1,PROGRAM MAKAN BERGIZI GRATIS UNTUK ANEUK ACEH\...,program makan bergizi gratis untuk aneuk aceh ...,"[program, makan, bergizi, gratis, untuk, aneuk..."
2,@abu_waras @prabowo Sdh pertengahan Januari 20...,abuwaras prabowo sdh pertengahan januari sampa...,"[abuwaras, prabowo, sdh, pertengahan, januari,..."
3,@bahlilngntot @tanyakanrl Agen mbg,bahlilngntot tanyakanrl agen mbg,"[bahlilngntot, tanyakanrl, agen, mbg]"
4,Program MBG = bukan bisnis. Ini gerakan sosial...,program mbg bukan bisnis ini gerakan sosial ya...,"[program, mbg, bukan, bisnis, ini, gerakan, so..."

In [84]:
stopwords = [
    'dan','di','yang','ke','dari','untuk',
    'ini','itu','atau','karena','ada',
    'the','and','of','to','is','in',
    'a','i','you','my','me'
]

def remove_stopwords(tokens):

    hasil = []

    for word in tokens:
        if word not in stopwords:
            hasil.append(word)

    return hasil


df['stopwords_removed'] = df['tokens'].apply(remove_stopwords)

display(df[['tokens', 'stopwords_removed']].head())

,tokens,stopwords_removed
0,"[surat, edaran, se, ditjen, pendis, kemenag, n...","[surat, edaran, se, ditjen, pendis, kemenag, n..."
1,"[program, makan, bergizi, gratis, untuk, aneuk...","[program, makan, bergizi, gratis, aneuk, aceh,..."
2,"[abuwaras, prabowo, sdh, pertengahan, januari,...","[abuwaras, prabowo, sdh, pertengahan, januari,..."
3,"[bahlilngntot, tanyakanrl, agen, mbg]","[bahlilngntot, tanyakanrl, agen, mbg]"
4,"[program, mbg, bukan, bisnis, ini, gerakan, so...","[program, mbg, bukan, bisnis, gerakan, sosial,..."

In [85]:
df['final_text'] = df['stopwords_removed'].apply(
    lambda x: ' '.join(x)
)

display(df[['final_text']].head())

                                          final_text
0  surat edaran se ditjen pendis kemenag nomor ta...
1  program makan bergizi gratis aneuk aceh penuhi...
2  abuwaras prabowo sdh pertengahan januari sampa...
3                   bahlilngntot tanyakanrl agen mbg
4  program mbg bukan bisnis gerakan sosial peduli...

In [93]:
vectorizer = TfidfVectorizer(ngram_range=(1,3), max_features=1500)
X_tfidf = vectorizer.fit_transform(df['final_text'])


print(f"Shape TF-IDF matrix: {X_tfidf.shape}")
print("\n")

Shape TF-IDF matrix: (15000, 1500)

In [94]:
features = vectorizer.get_feature_names_out()

# Buat DataFrame TF-IDF, baris = dokumen, kolom = fitur
tfidf_df = pd.DataFrame(X_tfidf.toarray(), columns=features)

# Ubah nama kolom jadi D1, D2, dst untuk dokumen (opsional)
tfidf_df.index = [f'D{i+1}' for i in range(tfidf_df.shape[0])]

# Transpose supaya term jadi baris dan dokumen jadi kolom
tfidf_table = tfidf_df.T
tfidf_table.columns.name = "Document"
tfidf_table.index.name = "Term"

# Tampilkan
# Hitung rata-rata TF-IDF tiap term di semua dokumen
term_means = tfidf_table.mean(axis=1)
# Pilih top 20 term
top_terms = term_means.sort_values(ascending=False).head(20).index
# Tampilkan hanya term tersebut
display(tfidf_table.loc[top_terms].round(4))

Document,D1,D2,D3,D4,D5,D6,D7,D8,D9,D10,...,D14991,D14992,D14993,D14994,D14995,D14996,D14997,D14998,D14999,D15000
Term,,,,,,,,,,,,,,,,,,,,,
mbg,0.0932,0.0000,0.0360,0.1863,0.0428,0.0000,0.0000,0.1007,0.0653,0.1027,...,0.0491,0.0946,0.1570,0.0592,0.0000,0.0458,0.0436,0.0375,0.0871,0.0687
program,0.0000,0.1557,0.0000,0.0000,0.0839,0.0970,0.1001,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.3081,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1347
makan,0.1898,0.1616,0.0733,0.0000,0.0871,0.1007,0.1039,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0868,0.0000,0.0000,0.0000,0.0000,0.0000
gratis,0.2029,0.1727,0.0000,0.0000,0.0000,0.1076,0.1110,0.2191,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0927,0.0000,0.0950,0.0000,0.0000,0.0000
bergizi,0.2107,0.1793,0.0000,0.0000,0.0000,0.2235,0.1153,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0963,0.0000,0.0986,0.0000,0.0000,0.0000
yg,0.0000,0.0000,0.4293,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0894,0.0000,0.0000
makan bergizi,0.2193,0.1867,0.0000,0.0000,0.0000,0.1164,0.1201,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.1003,0.0000,0.0000,0.0000,0.0000,0.0000
bergizi gratis,0.2213,0.1884,0.0000,0.0000,0.0000,0.1174,0.1212,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.1012,0.0000,0.1036,0.0000,0.0000,0.0000
makan bergizi gratis,0.2230,0.1898,0.0000,0.0000,0.0000,0.1183,0.1221,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.1019,0.0000,0.0000,0.0000,0.0000,0.0000
program mbg,0.0000,0.0000,0.0000,0.0000,0.1163,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.4268,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1866
anak,0.0000,0.0000,0.0000,0.0000,0.1163,0.1344,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.1158,0.0000,0.0000,0.0000,0.0000,0.0000
program makan,0.0000,0.2198,0.0000,0.0000,0.0000,0.1370,0.1413,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
prabowo,0.0000,0.0000,0.1041,0.0000,0.0000,0.0000,0.0000,0.0000,0.1888,0.2968,...,0.0000,0.0000,0.4540,0.0000,0.3695,0.1324,0.0000,0.0000,0.0000,0.0000
ga,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.4541,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
program makan bergizi,0.0000,0.2315,0.0000,0.0000,0.0000,0.1443,0.1489,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
buat,0.0000,0.0000,0.0000,0.0000,0.1317,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.1410,0.0000,0.0000,0.0000,0.0000
aja,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
sekolah,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.2014,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
keracunan,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
jadi,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000

In [95]:
from sklearn.decomposition import LatentDirichletAllocation

# model LDA
lda = LatentDirichletAllocation(
    n_components=5,
    random_state=42
)

# training LDA pakai TF-IDF
lda.fit(X_tfidf)

print("LDA berhasil dibuat")

LDA berhasil dibuat

In [96]:
# ambil nama fitur/kata
fitur = vectorizer.get_feature_names_out()

# tampilkan topik
for i, topik in enumerate(lda.components_):

    print(f"\nTopik {i+1}")

    kata_topik = [
        fitur[index]
        for index in topik.argsort()[-10:]
    ]

    print(kata_topik)

Topik 1
['dengan', 'kerja', 'lebih', 'tidak', 'ekonomi', 'lanjutkan mbg', 'lanjutkan', 'program mbg', 'program', 'mbg']

Topik 2
['program makan bergizi', 'program', 'program makan', 'makan bergizi gratis', 'bergizi gratis', 'makan bergizi', 'makan', 'bergizi', 'mbg', 'gratis']

Topik 3
['generasi', 'makan', 'sehat', 'makan bergizi', 'gizi', 'bergizi', 'anak', 'program', 'makanbergizigratis', 'indonesia']

Topik 4
['kalo', 'mau', 'sama', 'ya', 'gak', 'buat', 'aja', 'ga', 'yg', 'mbg']

Topik 5
['sekolah', 'siswa', 'pak', 'menu', 'keracunan mbg', 'multibankio', 'prabowo', 'yg', 'keracunan', 'mbg']